common_test.go
=> Fixes typo in test messages

bin/mint-client-https/main.go, bin/mint-server-https/main.go, conn.go
Make some fixes so that Mint works with HTTPS.
=> Add https demo and fix read buffers.

alert.go, bin/mint-client-https/main.go, conn.go, record-layer.go, record-layer_test.go, tls_test.go
- Add tls_test from go/crypto/tls
- Update code to handle alertCloseNotify.
- Fix up the logic around when to return EOF on reads
=> Fix up some of the logic around buffering/closing

bin/mint-client-https/main.go, bin/mint-client/main.go, bin/mint-server-https/main.go, bin/mint-server/main.go, conn.go
- make init explicit
- add configurability
=> Update test commands to work

README.md
I haven't worked out how to get mint a certificate yet.
=> Some updates to the instructions

common.go, conn.go, conn_test.go, crypto.go, crypto_test.go, extensions_test.go, handshake-messages.go, handshake-messages_test.go, log.go
There may still be some bugs in here, but this at least does a basic handshake with NSS, both as client and server (with NSS in complementary roles).
=> Support for draft-13

crypto.go
Fixes bug where this error occurs ~1% of the time:
```
tls.keyshare: Key exchange value has the wrong size
```
=> Properly pad keyshares and shared secrets.

common.go, conn.go, conn_test.go, extensions.go, extensions_test.go
=> Add support for ALPN

conn.go, extensions.go, extensions_test.go
=> Fix PSK compatibility issues

conn.go
Just a first stab at this, getting the basics done.
=> Implement Conn.ConnectionState method.

common.go, conn.go, conn_test.go, crypto.go, crypto_test.go, extensions.go, extensions_test.go, handshake-layer_test.go, handshake-messages.go, handshake-messages_test.go, handshake.go
This PR makes public some enums that might be useful for configuring clients and servers.
=> Export enums

conn.go, conn_test.go, crypto.go, handshake-messages.go, handshake-messages_test.go, handshake.go, negotiation.go, negotiation_test.go
=> Add support for client authentication

conn.go, conn_test.go, handshake.go, negotiation.go, negotiation_test.go
=> Allow indirection of PSK storage

client-state-machine.go, conn.go, conn_test.go, handshake-messages.go, handshake-messages_test.go, negotiation.go, state-machine.go
=> Add obfuscated ticket age checks

bin/mint-server/main.go, conn.go, tls.go
1. Log self-generated certs
2. Have the test server auto-generate with name="localhost"
3. Make Accept translate AlertNoAlert to nil
4. The test server auto-exits after writing once.
=> Make demo programs sort of work:

common.go
=> FFDHE8192 id is 260

client-state-machine.go, conn.go, conn_test.go, server-state-machine.go, state-machine.go
So you can see, not for merging
=> WIP: external extensions

.circleci/config.yml, common_test.go, conn_test.go, state-machine_test.go
No functional changes, but this will make the test output look nicer (and easier to debug) when tests fail.
=> use test helper functions and sub tests

client-state-machine.go, common.go, conn.go, conn_test.go, server-state-machine.go, state-machine.go
=> introduce a way to ask mint about the state of the handshake

client-state-machine.go, common.go, common_test.go, conn.go, conn_test.go, dtls.go, frame-reader.go, handshake-layer.go, handshake-layer_test.go, handshake-messages.go, negotiation.go, record-layer.go, record-layer_test.go, server-state-machine.go, state-machine.go, state-machine_test.go
will handle the framing and has at least rudimentary reassembly
of out of order packets. I think it's worth getting it in to
avoid a long-lived branch.
@bifurcation this probably isn't quite ready, but I think worth a first look
=> Beginning of DTLS support. This doesn't work properly yet, but it

bin/mint-client/main.go, client-state-machine.go, common.go, dtls.go, handshake-messages.go, handshake-messages_test.go, record-layer.go, record-layer_test.go, server-state-machine.go, tls.go
- Modify the command line programs to do DTLS
- Update ClientHello to have the right version and cookie field
- Fix the epoch handling in encryption and decryption
=> DTLS interop with NSS (Mint as Client)

syntax/README.md, syntax/decode.go, syntax/decode_test.go, syntax/encode.go, syntax/encode_test.go, syntax/tags.go
=> Add support for encoding and decoding structs with varint and 0-length

README.md, client-state-machine.go, common.go, common_test.go, conn.go, conn_test.go, crypto_test.go, dtls.go, extensions_test.go, frame-reader.go, frame-reader_test.go, handshake-layer.go, handshake-layer_test.go, log_test.go, negotiation.go, negotiation_test.go, record-layer.go, record-layer_test.go, server-state-machine.go, state-machine.go, state-machine_test.go, timer.go
This is really enormous, and as noted in the comments, not quite done, but I also want to get it landed before we have more rebase issues.
@bifurcation: LMK if you want me to file issues for the known deficiencies
=> Enhance dtls2

client-state-machine.go, common_test.go, conn.go, conn_test.go, crypto.go, handshake-layer.go, handshake-layer_test.go, record-layer.go, record-layer_test.go, server-state-machine.go, state-machine.go
This rolls up all the changes for draft-28 as well.
Needs review though.
=> QUIC record layer changes

crypto_test.go
=> Fix key share pub/priv order in test.
