bin/mint-server-https/main.go
common_test.go
conn.go
crypto.go
crypto_test.go
extensions_test.go
handshake-layer.go
handshake-layer_test.go
handshake-messages.go
handshake-messages_test.go
log.go
log_test.go
record-layer.go
record-layer_test.go
tls.go

With this PR:
* Test coverage is 100% except for `conn.go` and `tls.go`
* `golint` and `go vet` are both clean (except for ciphersuites)
* Logging can be configured with an environment variable (default off) 
Fixes #11 
Fixes #9

Testing and logging improvements

---

crypto.go
tls_test.go

- Set notBefore / notAfter
- Require a name to be provided

Make better self-signed certs

---

conn.go
crypto.go
handshake-messages.go
handshake-messages_test.go

Instead of using the certVerify hash to compute all the hashes in the certVerify computation, use the PRF hash for everything except the final hash.
NB: We should probably just use the pre-hashed transcript from the `cryptoContext` (i.e., `ctx.hX` for some `X`), but rather than figure that out, this patch just uses the right hashes directly.

Use correct algorithms in CertVerify signature verification

---

bin/mint-server-http2/main.go

HandleConn doesn't exist in server.go (any more?).  But ServeConn is there and exported.

Use ServeConn

---

common.go
common_test.go
conn.go
conn_test.go
extensions.go
extensions_test.go
handshake.go
log.go
negotiation.go
negotiation_test.go

This PR pulls most of the server handshake out into a set of negotiation functions that can be individually unit-tested, for more readability and better test coverage.
This PR also makes PSK support more correct by adding support for the PskKeyExchangeModes extension.

Simplify server handshake

---

state-machine.go

We have enforcement of ALPN matching for resumption / PSK, but weren't populating the field in the `PreSharedKey` object.

Store ALPN in the session cache

---

common_test.go
conn.go
conn_test.go
frame-reader.go
frame-reader_test.go
handshake-layer.go
log.go
record-layer.go
tls_test.go

is a lot less greedy.
- Build a generic framed data state machine used by both the
record and the handshake layers.
- Allow Read() to return whenever any data is available rather
than when all the data is available.
- The frameReader can return frameWouldBlock when it tries
to read off a reader and gets 0 bytes. This is handled
in the upper layers by looping and controlled by a Nonblocking
config parameter.
This code doesn't support nonblocking at the top-level API yet,
but I'll be adding that next.

Big refactor of the I/O discipline. The big change is that reading

---

conn.go

Note that this is an API change in that the default in the
configuration is for this value to be false. Thus, people who
were previously relying on the default (broken) behavior for
this configuration flag will not get session tickets. Alternately,
we can remove this config flag and replace it with one that
goes the other way.

Make the SendSessionTicket configuration parameter actually work.

---

common.go
crypto.go
handshake-messages.go
handshake-messages_test.go
state-machine.go

This just changes the version number and adds support for ticket nonces, which should be enough.  
However, draft-20 support never really got interop tested, so let's do some testing with other stacks before merging.

Support draft-21

---

common.go

I'd like to be able to log the cipher suite negotiated in the handshake. Having a string representation of the `CipherSuite` would be very handy for that.

implement a string representation of the CipherSuite

---

conn.go
extensions.go
server-state-machine.go
state-machine.go
state-machine_test.go

By setting a `CookieHandler`, the user can provide an opaque byte-slice that is used as a cookie in the HRR, and validate the cookie when the client echos it in the CH. Mint passes a pointer to the `Conn` to the methods that generate and validate the cookie. It's the responsibility of the cookie handler implementation to decide if a cookie should be sent for this specific connection..
If `Config.RequireCookie` is set to `true`, but no `Config.CookieHandler` is defined, a default cookie handler is used (the one that was already implemented). The default handler uses 32 random bytes as a cookie.
I'm not sure where the appropriate place would be to test a failed cookie validation. I guess *state-machine_test.go* would be the right place, but the tests there only cover successful handshakes. …

implement a CookieHandler to manually set and validate cookies

---

client-state-machine.go
conn.go
conn_test.go
handshake-layer.go
server-state-machine.go
state-machine.go
state-machine_test.go
tls.go
tls_test.go

Fixes #143. Should be merged after #141.
In non-blocking mode, `Handshake()` now returns after every state transition with `AlertNoAlert`. If `Handshake` is called, but would block while reading a new record, it returns `AlertWouldBlock`.
The state of the handshake is now returned by `Conn.GetHsState()`.
@ekr, @bifurcation: What do you think about this?

do not automatically advance state in non-blocking mode

---

syntax/decode.go
syntax/decode_test.go
syntax/encode.go
syntax/encode_test.go
syntax/pointer-fail_test.go

I think this will offer a path to implementing the `select` syntax, e.g., to make encode/decode of `HandshakeMessage` more elegant.

Add explicit marshal/unmarshal to the TLS syntax module

---

conn.go
conn_test.go

This is more consistent with how the `Config` works (e.g. for the `Config.CookieProtector` and the `Config.CookieHandler`. Furthermore, this refactoring was necessary for implementing the certificate verification in #170.

set the extension handler in the Config, not on the Conn

---

client-state-machine.go
conn.go
conn_test.go
server-state-machine.go

Depends on #170. Replaces #163.
This PR replaces the `Config.AuthCertificate` with a `Config.VerifyPeerCertificate`. The purpose of both methods is similar (although `AuthCertificate` never actually worked). `VerifyPeerCertificate` is supposed to work exactly like the `tls.Config.VerifyPeerCertificate` [in the standard library](https://golang.org/pkg/crypto/tls/#Config).
Note that currently for the server, the `verifiedChains` argument for `VerifyPeerCertificate` is always nil. This is consistent with the way we implement client auth (by just requiring the client so send *any* certificate), which is one of the ways the Go standard library allows client certificate verification. I created #171 to track this, and I'll be happy to contribute some code to resolve this issue in the future.
The …

implement the VerifyPeerCertificate mint.Config option

---

client-state-machine.go
conn.go
conn_test.go
server-state-machine.go
state-machine.go

Depends on #172. Fixes #81. Closes #162.
This is a better version of #162, and it's probably the better way to first implement all the verification logic.
The behavior should be analogous to the Go standard library.
I also renamed the `Conn.State()` to `Conn.ConnectionState()`, to make mint more consistent with the `tls.Conn` from the standard library.

expose the peer certificates and the verified chain in the connection state

---

conn.go

handshake is complete, non-blocking mode or not.

The API needs to throw an error whenever you try to Read() before the

---

bin/mint-client-https/main.go
bin/mint-client/main.go
bin/mint-server-https/main.go
bin/mint-server/main.go
conn_test.go
crypto.go
negotiation_test.go
state-machine_test.go

This PR cleans up fallout from PR#167 and PR#170. Specifically:
1. Exposes a public MakeNewSelfSignedCert API because need that several places.
2. Modifies the server programs so that they explicitly call the new API (otherwise they don't work).
3. Adds a flag to the clients to skip cert verification.
In future, it would help if we were more careful

Restore self signing utils

---

client-state-machine.go
conn.go
server-state-machine.go
state-machine.go
state-machine_test.go

This PR privatizes all handshake states, thereby reducing our [public API](https://godoc.org/github.com/bifurcation/mint) by roughly 20%.
In general, I think we should only expose objects and functions that are actually needed to interact with mint. There is **a lot** more that we can privatize, so this PR is just a small step in this direction. If we agree that this is the path we want to go, I'll be happy to contribute more PRs.
@bifurcation, @ekr: What do you think?

privatize handshake states

---

client-state-machine.go
common.go
conn_test.go
handshake-messages.go
handshake-messages_test.go
negotiation.go
record-layer.go
record-layer_test.go
server-state-machine.go

This should make mint interoperable for draft-28 changes in *TLS*.  I can take a swing at implementing the record layer changes for DTLS, but that is a far bigger change and I'd like to do that separately.  (Either that, or get @ekr to do those because I made the changes in NSS.)

TLS 1.3 Final

---

syntax/decode.go
syntax/decode_test.go
syntax/encode.go
syntax/success_test.go
syntax/tags.go
syntax/tags_test.go

Required for implementing MLS structs.  A pointer field in a struct can be tagged as "optional".  The null optional ("0x00") corresponds to the nil pointer.  Non-nil pointers are marshaled / unmarshaled as usual, with a 0x01 octet prefixed.

Add support for optional<T>

---

syntax/decode.go
syntax/encode.go
syntax/success_test.go
syntax/tags.go

The support for optional<T> in #210 omitted the case where the optional thing is a syntax.Marshaler.  This PR fixes that case.

Handle optional Marshalers

---

syntax/decode.go
syntax/encode.go
syntax/tags.go
syntax/tags_test.go

Depends on #212 
This PR cleans up a few things about how struct tags are handled:
* Instead of parsing into a generic `map[string]int`, we now use a struct
* This struct is used in place of `encOpts` and `decOpts`, since they're the same anyway
* Tags are now checked for consistency at parse time
* Slice encoding is now a bit more systematic

Options cleanup

---

syntax/decode.go
syntax/decode_test.go
syntax/encode.go
syntax/encode_test.go
syntax/success_test.go
syntax/tags.go

For example, with this change, an "enum" type can validate that the value to be encoded or the just-decoded value is a valid enum value, just by defining a single method:
```
func (e Enum) ValidForTLS() error {
if (e == KnownEnumValue0) || (e == KnownEnumValue0) || ... {
return nil
}
return fmt.Errorf("Unknown enum value")
}
```
This facility could also, of course, be used to validate more advanced types.

Allow validation at TLS marshal/unmarshal time

---

.circleci/config.yml
syntax/decode.go
syntax/decode_test.go
syntax/encode.go
syntax/encode_test.go
syntax/success_test.go
syntax/tags.go

This is totally off-piste with regard to the specification, but so are many of the features we have in this repo.  The encoding strategy here effectively treats a `map[A]B` as a `[]struct{a A; b B}`, that is, as a sequence of key/value pairs.  In order to be canonical, the encoder sorts the pairs lexically by key.

Allow serialization of Go maps

---

go.mod

Result of:
```
go mod init
go mod tidy
```
Required for things like `go test` in recent versions of Go.

Add Go module metadata
